### ISSUE TITLE
Setting environment variable in docker image does not do anything

### ISSUE THREAD

**Issue by ballermc** [sparkison/m3u-editor#100]
## Describe the bug

When I set the environment variables from the docs, it did not change at all and still used the ones m3u-editor generated.

## To Reproduce

1. Use docker compose setup for m3u-editor
2. Specify the variables you want to set
3. Start the docker instance
4. check console and see that it never changed.

## Expected behavior

Change to use the ones I set

## Actual behavior

Uses default m3u-editor file

## docker-compose.yml contents

```yaml
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - APP_URL=https://m3u-editor.mydomain.com
      # This is used for websockets and in-app notifications
      # Set to your machine/container IP where m3u editor will be accessed, if not localhost
      - REVERB_HOST=m3u-editor.mydomain.com
      - REVERB_SCHEME=https
    volumes:
      # This will allow you to reuse the data across container recreates.
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - /opt/data/m3u-editor:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.m3u-editor.rule=Host(`m3u-editor.mydomain.com`)"
      - "traefik.http.routers.m3u-editor.entrypoints=websecure"
      - "traefik.http.routers.m3u-editor.tls.certresolver=myresolver"
      - "traefik.http.routers.m3u-editor.service=m3u-editor"
      - "traefik.http.services.m3u-editor.loadbalancer.server.port=36400"
      - "traefik.http.services.m3u-editor.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.Host=m3u-editor.mydomain.com"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.X-Forwarded-Host=m3u-editor.mydomain.com"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.m3u-editor-websockets.rule=Host(`m3u-editor.mydomain.com`) && PathPrefix(`/app`)"
      - "traefik.http.routers.m3u-editor-websockets.entrypoints=websecure"
      - "traefik.http.routers.m3u-editor-websockets.tls.certresolver=myresolver"
      - "traefik.http.routers.m3u-editor-websockets.service=m3u-editor-websockets"
      - "traefik.http.routers.m3u-editor-websockets.middlewares=websocket"
      - "traefik.http.services.m3u-editor-websockets.loadbalancer.server.port=36800"
      - "traefik.http.services.m3u-editor-websockets.loadbalancer.server.scheme=http"
    profiles:
      - stremio
      - all

```

## Container/Host Logs

N/A

## Additional context

![Image](https://github.com/user-attachments/assets/72e139ef-ca13-48ea-99a7-56508ff0db60) 

![Image](https://github.com/user-attachments/assets/8e65543f-beed-4712-9df9-81c32fea7090)
