### ISSUE TITLE
Playlist sync - 0 channels

### ISSUE THREAD

**Issue by djrarky** [sparkison/m3u-editor#160]
Hey mate, 

Apologies, came back to figuring out the catch-up process, but found after migrating to 0.5.8, unfortunately the sync has deleted my playlist changes. 
I was trying to work from dev, but the behavior is the same. 

![Image](https://github.com/user-attachments/assets/f7f831e6-d694-462d-ae88-dd148530fe34)

I had created the following groups, and they no longer have any channel mappings assigned - and the channels themselves I've updated, these configurations have been lost too. 

![Image](https://github.com/user-attachments/assets/d51461e7-b082-4c1f-9a21-0dc9f5cd452b)

I'm unsure where the logs are stored, I can pull those if you're able to share with me. 
This issue is reproducible. 

When I migrate back to 0.5.7 with the same volume, the data is still gone. 

But, should I restore from backup, the 0.5.7 image continues to work fine without issue. Syncs are performed successfully, so at the moment I remain on 0.5.7. 

The issue is also the same on the dev channel should I migrate to dev from 0.5.7, or 0.5.8 with the missing data.

Should I take a backup in 0.5.7, and restore into either 0.5.8 or dev, the gui gives me a server 500 error, and I see the following logs at container startup. 

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: dev-m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - REVERB_HOST=[domain]
      - REVERB_SCHEME=https
      - APP_URL=https://[domain]
      - OCTANE_HTTPS=true
#      - FFMPEG_DEBUG=true
    volumes:
      - ./m3u-editor:/var/www/config
    restart: unless-stopped
    expose:
      - 36400
      - 36800
```

## Container/Host Logs

```log
🗂️ Enabling SQLite WAL mode...

In Connection.php line 825:

  SQLSTATE[HY000]: General error: 26 file is not a database (Connection: sqli
  te, SQL: PRAGMA journal_mode=WAL;)


In Connection.php line 565:

  SQLSTATE[HY000]: General error: 26 file is not a database


The 'jobs' connection has been set as [wal] journal mode.

💾 Running migrations...

In Connection.php line 825:

  SQLSTATE[HY000]: General error: 26 file is not a database (Connection: sqli
  te, SQL: select exists (select 1 from sqlite_master where name = 'migration
  s' and type = 'table') as "exists")


In Connection.php line 407:

  SQLSTATE[HY000]: General error: 26 file is not a database
```
