### ISSUE TITLE
WebSockets are still enabled even when BROADCAST_CONNECTION is set to null.

### ISSUE THREAD

**Issue by Freekers** [sparkison/m3u-editor#163]
## Describe the bug

According to the documentation, setting the BROADCAST_CONNECTION environment variable to null should disable WebSocket functionality. However, in the Developer Tools, I still see connection attempts related to WebSockets.

## To Reproduce

Set BROADCAST_CONNECTION=null in your docker-compose (see below)

## Expected behavior

Websockets should be disabled after setting the BROADCAST_CONNECTION environment variable to null

## Actual behavior

Websockets are still enabled after setting the BROADCAST_CONNECTION environment variable to null

## Screenshots

![Image](https://github.com/user-attachments/assets/698ffe3e-ae39-4d10-92b1-89e7130501d4)

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    environment:
      - BROADCAST_CONNECTION=null
```
