### ISSUE TITLE
EPG Mapping Fails with Syntax Error in Dev Branch (PostgreSQL Backend)

### ISSUE THREAD

**Issue by Freekers** [sparkison/m3u-editor#164]
## Describe the bug

I took a sneak peek at the current dev branch because I was curious about the PostgreSQL implementation.
Everything seems to be working well, except for the EPG mapping. I'm not sure if you're already aware, but triggering an EPG mapping results in a syntax error (see below).

## To Reproduce

1. Run dev branch with Postgres enabled
2. Fetch Channels and EPG list
3. Try to map EPG to Channels 

## Expected behavior

EPG should be mapped to Channels

## Actual behavior

EPG mapping fails with syntax error

## Screenshots

![Image](https://github.com/user-attachments/assets/1d1da122-b4a0-46ef-b945-de19557347d1)

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: m3u-editor
    environment:
      - BROADCAST_CONNECTION=null
      - ENABLE_POSTGRES=true        
      - PG_DATABASE=m3u
      - PG_USER=m3u
      - PG_PASSWORD=m3u
      - PG_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_DATABASE=m3u
      - DB_USERNAME=m3u
      - DB_PASSWORD=m3u
    volumes:
      - /opt/docker/m3u/data:/var/www/config
      - /opt/docker/m3u/db:/var/lib/postgresql/data
    restart: unless-stopped
```
