### ISSUE TITLE
Playlist works locally, but not as Network Stream in VLC

### ISSUE THREAD

**Issue by vdrover** [sparkison/m3u-editor#183]
## Describe the bug

I'm using a custom domain, and typically (xteve, streammaster, etc) would take the URL of the playlist and load it into VLC as a Network Source to test playback. It's a quick and easy way to test the proxy/editor without having to add to Plex/Emby/Jellyfin.

For some reason, if I use the download URL of the m3u-editor playlist (eg: https://my.domain.com/9f08w8fd-65e7-4h01-b127-ea4b61hb42e6/playlist.m3u) as a network Source, the channels never load in VLC and I cannot test playback.

Oddly, simply download the M3U and opening it VLC allows the channels to load, and playback to occur as expected. The URL also works if i add it directly to Plex/Emby/Jellyfin.

## To Reproduce

See above

## Expected behavior

Network stream to work in VLC

## Actual behavior

Title of playlist loads in VLC, but no channels.

## docker-compose.yml contents
```
  # M3U editor
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: m3u-editor
    networks:
      - npm_proxy
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - APP_URL=https://m3u.mydomain.com
      - REVERB_HOST=m3u.mydomain.com
      - REVERB_SCHEME=https
    volumes:
      - $DOCKERDIR/appdata/m3u-editor:/var/www/config
      - $DOCKERDIR/appdata/m3u-editor/channel-logos:/var/www/html/public/logos
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
```

## Additional context
I am using nginx proxy manager and have set my custom domain using port 36400. Not sure if i need to be doing something with port 36800.

![Image](https://github.com/user-attachments/assets/11f0c4c3-f5fd-40bf-8fe3-ae3a855fcb5e)
