### ISSUE TITLE
TZ env variable not respected.

### ISSUE THREAD

**Issue by vdrover** [sparkison/m3u-editor#190]
I've set the TZ in my YML file, but the timestamps in the logs still show UTC. Observed in both the `latest` and `dev` builds. 

```
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: m3u-editor
    networks:
      - npm_proxy
    environment:
      - TZ=TZ=America/Chicago
      - PUID=$PUID
      - PGID=$PGID
      - APP_URL=https://domain.com
      - REVERB_HOST=domain.com
      - REVERB_SCHEME=https
      - APP_DEBUG=true
    volumes:
      - $DOCKERDIR/appdata/m3u-editor:/var/www/config
      - $DOCKERDIR/appdata/m3u-editor/channel-logos:/var/www/html/public/logos
    restart: unless-stopped
    ports:
      - 36400:36400
      - 36800:36800
```
