### ISSUE TITLE
All channels are flagged as supporting catch-up, regardless of whether they actually do

### ISSUE THREAD

**Issue by notjezza** [sparkison/m3u-editor#207]
## Describe the bug

When using a playlist generated by m3u Editor, every channel is flagged as supporting catch-up and shows an icon on the channel logo in my IPTV client (UHF), in both the iOS and TVOS apps. This causes issues as the player UI changes for catch-up streams/channels and certain settings/behaviours work incorrectly, in addition to not being able to visually identify which channels actually support it.

## To Reproduce

1. Create a playlist via XC API (Doesn't matter whether HLS or TS output is selected, or whether proxied or not)
2. Process playlist after config, then load URL into IPTV client
3. After IPTV client loads playlist from m3u Editor instance, every channel is flagged as supporting catchup
4. Custom playlist with curated selection of channels also suffers bug - initial test was with 1 channel that did not support catchup, which appeared with catch-up icon in IPTV client.

## Expected behavior

Only channels that actually support catchup as indicated in the XC API response JSON should do the same when parsed/processed by m3u Editor and that playlist is imported to IPTV client.

When adding XC API server directly to client, all channels display/behave correctly - only a few support catch-up, and those show the icon then have the different player UI once loaded.

## Actual behavior

Every channel in a m3u editor playlist is flagged as supporting catch-up.

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    network_mode: host
    container_name: m3u-editor
    environment:
      - TZ=MyCountry/MyCityTimezone
      - APP_URL=http://public.ip.removed.here # or http://192.168.0.123 or https://your-custom-tld.com
      # This is used for websockets and in-app notifications
      # Set to your machine/container IP where m3u editor will be accessed, if not localhost
      - REVERB_HOST=public.ip.removed.here # or 192.168.0.123 or your-custom-tld.com
      - REVERB_SCHEME=http # or https if using custom TLD with https
    volumes:
      # This will allow you to reuse the data across container recreates
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - ./data:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
networks: {}
```

## Additional context

When I call 'the /player_api.php&action=get_live_streams' endpoint on the XC server, the output of a channel which supports catch-up has value of 1 for key "tv_archive" and some >0 value for 'tv_archive_duration'. For example:

{
"num": 7896,
"name": "UK| TNT SPORT 1 HD",
"stream_type": "live",
"stream_id": 13780,
"stream_icon": "https://lo1.in/uk/tntsport.png",
"epg_channel_id": "tntsports1.uk",
"added": "1590795820",
"is_adult": "0",
"category_id": "119",
"custom_sid": "",
"tv_archive": 1,
"direct_source": "",
"tv_archive_duration": "4"
},

When a channel does not support catch-up, both values are 0.

{
"num": 7897,
"name": "UK| TNT SPORT 1 HD [BK]",
"stream_type": "live",
"stream_id": 6202,
"stream_icon": "https://lo1.in/uk/tntsport.png",
"epg_channel_id": "tntsports1.uk",
"added": "1662463034",
"is_adult": "0",
"category_id": "119",
"custom_sid": "",
"tv_archive": 0,
"direct_source": "",
"tv_archive_duration": 0
},

Pretty straightforward how it's defined via XC. What I can see from looking at the m3u coming out of m3u editor is that every entry includes the parameter timeshift="0" and this might be the source of the issue.

Some quick googling suggests that timeshift="x" is used to enable catch-up for a channel, while tvg-shift="x" can be used to offset the EPG.
