### ISSUE TITLE
High memory consumption in browser

### ISSUE THREAD

**Issue by YoBii** [sparkison/m3u-editor#217]
## Describe the bug

After a while of using m3u-editor in Firefox (librewolf) the interface becomes increasingly unresponsive. Checking the browser's task manager I saw the website/interface consuming 5GB of memory. 

## To Reproduce

I have around 2700 channels of which 500 are enabled.  
My EPG file is rather large. It's 14 days of data for most channels available in my country resulting in a size of around 500MB. 

Unload the tab and reopen it -> 200-300MB memory usage in browser's task manager. 

Click around in the interface for a while, switch between enabled/disabled/all channels in main channel view, open some groups -> observed memory usage in browser's task manager grows to multiple GB. Loading views takes longer. Opening editing panel and saving entry takes longer etc. 

## Expected behavior

The interface is responsive at all times and doesn't consume several GB of memory.

## Actual behavior

The interface becomes increasingly unresponsive as the browser is committing more memory while  you use the interface and do do stuff like switching between views. 
I can't quite quantify this but it appears the cpu usage bursts while loading views also become more significant in amplitude and duration. I can only see this in the browser's task manager which isn't that great (no graphs) as the load is insignificant for my system as a whole. 

The docker container itself doesn't show any abnormal cpu or memory usage. Only the php process spikes for a short duration when handling a request. 

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - TZ=Europe/Berlin
      - APP_URL=http://localhost # or http://192.168.0.123 or https://your-custom-tld.com
      # This is used for websockets and in-app notifications
      # Set to your machine/container IP where m3u editor will be accessed, if not localhost
      - REVERB_HOST=localhost # or 192.168.0.123 or your-custom-tld.com
      - REVERB_SCHEME=http # or https if using custom TLD with https
    volumes:
      # This will allow you to reuse the data across container recreates
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - /opt/m3u-editor/data:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
networks: {}
```

## Additional context

Let me know if I can provide other useful information.
