### ISSUE TITLE
Channel Preview not working anymore

### ISSUE THREAD

**Issue by Serph91P** [sparkison/m3u-editor#228]
## Describe the bug

After some of the recent versions the preview of the stream suddenly stopped.

## To Reproduce

Try to play channel in the preview
Looks to me it has something to do with the proxy url overwrite?

## Expected behavior

Channel plays

## Actual behavior

Error message  MEDIA_ERR_SRC_NOT_SUPPORTED

## Browser Log:
Sorry for german log :D
```Log
Mixed Content: Upgrade der unsicheren Anzeige-Anfrage 'http://gluetun:36400/stream/MQ.ts' zur Verwendung von 'https'
[MQ.ts](http://gluetun:36400/stream/MQ.ts)
Mixed Content: Upgrade der unsicheren Anzeige-Anfrage 'http://gluetun:36400/stream/MQ.ts' zur Verwendung von 'https'
[MQ.ts](http://gluetun:36400/stream/MQ.ts)
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
```

## docker-compose.yml contents

```yaml
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_URL=https://redacted
      - REVERB_HOST=redacted
      - REVERB_SCHEME=https
      - PROXY_URL_OVERRIDE=http://gluetun:36400
      - TZ=Europe/Berlin
      - ENABLE_POSTGRES=true               # <----- start here
      - PG_DATABASE=redacted # <----- DB name
      - PG_USER=redacted           # <----- DB user
      - PG_PASSWORD=redacted # <----- DB password
      - PG_PORT=5432           # <----- DB port (optional, defaults to 5432)
      - DB_CONNECTION=pgsql                # <----- set to `pgsql` (default is `sqlite`)
      - DB_HOST=localhost                  # <----- make sure set to `localhost`
      - DB_PORT=5432           # <----- using default Postgres port
      - DB_DATABASE=redacted # <----- should match `PG_DATABASE`
      - DB_USERNAME=redacted       # <----- should match `PG_USER`
      - DB_PASSWORD=redacted # <----- should match `PG_PASSWORD`
    volumes:
      - m3ueditor-config:/var/www/config
      - m3upgdata:/var/lib/postgresql/data
    devices:
      - /dev/dri:/dev/dri
```
