### ISSUE TITLE
Since the latest image released - my container has been erroring out and exiting

### ISSUE THREAD

**Issue by 39416** [sparkison/m3u-editor#229]
## Describe the bug

I recently had watchtower do an update to the m3u editor docker image and the one it pulled on the 7th of this month has this error when starting up...exec /usr/local/bin/start-container: exec format error - this occurs for about 20 lines in the log then times out and the container exits and stops with error code 1.

## To Reproduce

1. Ubuntu UTM VM on Mac mini M2 Pro
2. Portainer and docker compose file
3. watchtower
4. version released on 07Jun2025

## Expected behavior

The container will come straight up and be accessible from the ip and port

## Actual behavior

Container errors out and crashes

## docker-compose.yml contents

```
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      # This is used for websockets and in-app notifications
      # Set to your machine/container IP where m3u editor will be accessed, if not localhost
      - REVERB_HOST=localhost
      # Uncomment and set to URL or IP if not localhost. Use full url, including http(s)
      #- APP_URL=http://localhost
      # Uncomment and set to true if using HTTPS
      #- OCTANE_HTTPS=false
    volumes:
      # This will allow you to reuse the data across container recreates
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - ./data:/var/www/config
    restart: unless-stopped
    ports:
      - 35500:35500 # app
      - 35800:35800 # websockets/broadcasting
networks: {}
```

## Container/Host Logs

```
exec /usr/local/bin/start-container: exec format error
```

## Additional context

wondering if this is a mismatch of the wrong OS type pulled, but why would it change from working for past month perfectly to this new state since the update of the image?
