### ISSUE TITLE
External Postgresql won't work via localhost

### ISSUE THREAD

**Issue by digitalSaj** [sparkison/m3u-editor#233]
## Describe the bug

Since localhost or 127.0.0.1 is not resolving to the docker container's parent host. If 127.0.0.1 / localhost is kept, connection keeps failing

## To Reproduce

in docker compose if suggested hostname is kept, it won't work
`      - DB_HOST=hostname            # <----- your Postgres instance hostname (localhost, 127.0.0.1, etc.)`

## Expected behavior

It took me a bit of time to figure this out. Hence raising this, so that the instructions/ docker compose be updated

## Actual behavior
I have currently set `DB_HOST=172.17.0.1 `and  added `host   all all 172.0.0.0/8 md5` to my pg_hba.conf. But I think properly changing the docker compose would be a better way.

## docker-compose.yml contents

```yaml
# docker-compose.yml contents here
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```

**Comment by sparkison** [comment]
does setting it to `localhost` work? I have a couple different instances, and they are all using `localhost`. Some are using a custom TLD with SSL, and the other is local server using gluetun. I can remove the `127.0.0.1` reference in the docs.

**Comment by sparkison** [comment]
the recommended setup has the following:
```
...
- DB_HOST=localhost                  # <----- make sure set to `localhost`
...
```

Looks like you're looking at the custom Postgres instance. So I'll get the `127.0.0.1` reference removed from there

**Comment by digitalSaj** [comment]
> Looks like you're looking at the custom Postgres instance. So I'll get the `127.0.0.1` reference removed from there

Right. What should be the best method to connect to the system's custom postgresql (not the docker's).
I was thinking of adding network_mode: host eg.
```
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    network_mode: host
    environment:
    ......
```
Or any other suggestion?

**Comment by fuzmik** [comment]
works on my stacked two services. im on arm64.
```
name: m3u-editor
services:
  m3u-editor:
    container_name: m3u-editor
    entrypoint:
      - start-container
    environment:
      APP_PORT: "36400"
      APP_TIMEZONE: America/Los_Angeles
      APP_URL: http://m3u-editor
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_CONNECTION: pgsql
      DB_DATABASE: m3ue
      DB_HOST: m3u-postgres.cosmos-m3u-editor-default
      DB_PASSWORD: *************
      DB_PORT: "5432"
      DB_USERNAME: **************
      ENABLE_POSTGRES: "false"
      PG_DATABASE: m3ue
      PG_PASSWORD: ***************
      PG_PORT: "5432"
      PG_USER: **************
      REVERB_HOST: m3u-editor.cosmos-m3u-editor-default
      REVERB_SCHEME: http
      TZ: America/Los_Angeles
      WWWGROUP: m3ue
      WWWUSER: m3ue
    hostname: m3u-editor
    image: sparkison/m3u-editor:latest-arm64
    networks:
      cosmos-m3u-editor-default: null
    ports:
      - mode: ingress
        target: 36400
        published: "36400"
        protocol: tcp
      - mode: ingress
        target: 36800
        published: "36800"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /usr/m3u-config-data
        target: /var/www/config
        bind:
          create_host_path: true
    working_dir: /var/www/html
  m3u-postgres:
    command:
      - postgres
    container_name: m3u-postgres
    entrypoint:
      - docker-entrypoint.sh
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DATABASE: m3ue
      POSTGRES_PASSWORD: **********
      POSTGRES_PORT: "5432"
      POSTGRES_USER: **********
      TZ: America/Los_Angeles
    hostname: m3u-postgres
    image: postgres:15.3
    networks:
      cosmos-m3u-editor-default: null
    ports:
      - mode: ingress
        target: 5432
        published: "65432"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: m3u-postgres-data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  cosmos-m3u-editor-default:
    name: cosmos-m3u-editor-default
    external: true
volumes:
  m3u-postgres-data:
    name: m3u-postgres-data
    external: true
```
