### ISSUE TITLE
Error when using Status field with local file post process step

### ISSUE THREAD

**Issue by a-teisseire** [sparkison/m3u-editor#241]
## Describe the bug

When using a local file as a Post Process step and one of the expected values is the Status, the local script never gets called and an error of type "Object of class App\\Enums\\Status could not be converted to string" appears in the logs

## To Reproduce

1. Go to 'Post processing'
2. Click on 'New Post process'
3. Select 'Local file'
4. Fill in a valid local file
5. In the Script Options, add a field "SYNC_STATUS" that pulls its value from "Status"
6. Attach the post process to a playlist
7. Run a synchronization on the playlist

## Expected behavior

The referenced script / program should execute with the parameters available as environment variables.

## Actual behavior

The script doesn't get executed, only the error above appears in the logs.

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: m3u-editor
    environment:
      - TZ=Etc/UTC
      - APP_URL=https://xxx.xxxx.xxx:8080
      - REVERB_HOST=xxx.xxxx.xxx
      - REVERB_PORT=8080
      - REVERB_SCHEME=https
    devices:
      - /dev/dri:/dev/dri # For ffmpeg transcoding
    volumes:
      - ./data:/var/www/config
      - ./scripts:/scripts # Location of the post process scripts
    restart: unless-stopped
```

My image only adds jq & mosquitto-clients to the container.

## Container/Host Logs

```log
{
  "exception": "[object] (Error(code: 0): Object of class App\\Enums\\Status could not be converted to string at /var/www/html/vendor/symfony/process/Process.php:336)
[stacktrace]
#0 /var/www/html/vendor/symfony/process/Process.php(249): Symfony\\Component\\Process\\Process->start()
#1 /var/www/html/app/Jobs/RunPostProcess.php(149): Symfony\\Component\\Process\\Process->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\RunPostProcess->handle()
...
}
```

## Additional context

The following exception appears in the logs exactly right after.

```log
{
  "exception": "[object] (Pusher\\PusherException(code: 0): Data decoding error. at /var/www/html/vendor/pusher/pusher-php-server/src/Pusher.php:798)
[stacktrace]
#0 /var/www/html/vendor/pusher/pusher-php-server/src/Pusher.php(441): Pusher\\Pusher->post()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php(161): Pusher\\Pusher->trigger()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(261): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->{closure:Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster::broadcast():160}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php(160): Illuminate\\Support\\Collection->each()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(93): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast()
...
}
```
