### ISSUE TITLE
Error starting container:  Host mode and Missing Encryption (solution included)

### ISSUE THREAD

**Issue by knaak** [sparkison/m3u-editor#4]
## Describe the bug

Using the docker-compose file on the main page, attempt to using docker-compose up to start the container.

## To Reproduce

1. Download the docker-compose.yml file from the Docker compose section of the documentation
2. Run docker-compose up to bring up the container

## Expected behavior

I expect that the container would run without error, however I observed two errors which prevented it from starting normally.

## Actual behavior

Two errors, firstly the "network_mode" : "host" gave me an error because the actual ports are specified.  

```ERROR: for m3u-editor  "host" network_mode is incompatible with port_bindings```

I disabled network_hosts by commenting out that line.  

Secondly, the container entered a restart loop indicating that there was no encryption key initialized.

```log
Illuminate\Encryption\MissingAppKeyException  No application encryption key has been specified.
2025-01-19 16:46:02,628 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

m3u-editor    | 2025-01-19 16:46:02,628 INFO success: laravel entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
m3u-editor    | 2025-01-19 16:46:02,629 INFO success: queue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
m3u-editor    | 2025-01-19 16:46:02,629 INFO success: reverb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
m3u-editor    |
m3u-editor    |   0   /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:83
m3u-editor    |   1   /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:399
m3u-editor    |   2   /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:81
m3u-editor    | 2025-01-19 16:46:02,672 WARN exited: laravel (exit status 1; not expected)
```

I solved this by logging into the docker container:

```docker exec -it <<id>> sh```

and running these commands:

```
php artisan key:generate
php artisan config:clear
php artisan config:cache
```

This allowed the container to start.

## docker-compose.yml contents

```yaml

version: "3.8"
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WWWUSER=sail
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=off
    volumes:
      - ./config:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      # - 36790:36790 # for queue (redis server) - not currently used
      - 36800:36800 # websockets/broadcasting
networks: {}
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```
