### ISSUE TITLE
Missing "Groups to Import" with preprocess playlist enabled

### ISSUE THREAD

**Issue by agupta7** [sparkison/m3u-editor#45]
## Describe the bug

I have a rather large playlist of ~300MB with ~2M lines.  This excellent actually devoured the entire thing pretty well for the live channels.  However, I'm struggling with missing VOD content.  What I've found out so far is that certain "Groups to import" are missing in the preprocess list.  I tried importing those groups by using a group prefix like "OSN*" but the "channels"/VOD content is still missing from the output playlist.  The "OSN*" prefix should have matched a group in movies as well as a group in tv shows.

In addition - this may be related or orthogonal to the OSN issue described above - the output playlist only has live channels and movies - there are no items being output with "/series/" in their URL.

## To Reproduce

1. Import new m3u playlist from either upload or URL.
2. Enable preprocess playlist option
3. Process the playlist so that the groups are populated.
4. Observe that certain groups are missing (OSN, ASIA etc).
5. Observe that those groups' channels/VOD content are also missing even if using the prefix to import feature.

## Expected behavior

All unique groups found in the source playlist are populated correctly.

## Actual behavior

Certain groups are missing - I'm not sure how or why.

## Screenshots

N/A

## docker-compose.yml contents

```yaml
version: "3.8"
services:
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      # This will allow you to reuse the data across container recreates.
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - m3u-editor_data:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
networks: {}
volumes:
  m3u-editor_data:
```

## Container/Host Logs
N/A

## Additional context

Tried with 0.2.14 on the master branch (66acdb50a5f3141028c53215d35844ed32e4fa46) as well as latest dev (45096f468b21ffa64628fa25a9169004e465082b)

Let me know what more information you need to debug.
