### ISSUE TITLE
Error 404: failed to open stream

### ISSUE THREAD

**Issue by knaak** [sparkison/m3u-editor#5]
## Describe the bug

When attempting to add my playlist to the application, I receive this erorr:
```
file_get_contents(http://live.iptvcanada.tv//playlist/[redacted]/[redacted]/m3u): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

and I am unable to add this m3u.  

## To Reproduce

Go to Playlists, add playlist, specify URL.

## Expected behavior

Expected playlist to be added

## Actual behavior

Received a 404.  Now, i logged into the container as it was running and ran this command:

```wget http://live.iptvcanada.tv//playlist/[redacted]/[redacted]/m3u_plus```

and it worked from within the container

```log
Connecting to live.iptvcanada.tv (181.233.124.54:80)
saving to 'm3u_plus'
m3u_plus             100% |****************************************************************************************************************************************************************************************************************************************| 2007k  0:00:00 ETA
'm3u_plus' saved
```

**Note that this M3U is very large with > 8000 channels.  I noticed that you have only tested to 4000.

I also added a public facing one, "iptv-org.github.io" and that worked correctly.   So outbound internet doesn't seem to be the problem.

## Screenshots

[Screenshot](https://imgur.com/a/LyHWQ2a)

## docker-compose.yml contents

```yaml
version: "3.8"
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WWWUSER=sail
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=off
    volumes:
      - ./config:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      # - 36790:36790 # for queue (redis server) - not currently used
      - 36800:36800 # websockets/broadcasting
networks: {}
```

## Container/Host Logs

No useful logs produced

```log
Error processing "iptv"
1 hour ago
file_get_contents(http://live.iptvcanada.tv//playlist/[redacted]/[redacted]/m3u): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

## Additional context

If you can provide some guidance on how to debug this, I can help to determine whether its related to the large file size or some other issue.  I can also provide you with my unredacted URL for your debugging if that helps.  I just don't want it posted publicly.
