### ISSUE TITLE
Cannot Process m3u

### ISSUE THREAD

**Issue by Serph91P** [sparkison/m3u-editor#56]
## Describe the bug

I added my m3u to the porgramm but as soon as it starts to process I get an curl error 28

## To Reproduce

Add my m3u I get from my iptv provide I guess? 

## Expected behavior

m3u gets processed

## Actual behavior

curl Error 28 hattens

## docker-compose.yml contents

```yaml
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      # This will allow you to reuse the data across container recreates.
      # Format is: <host_directory_path>:<container_path>
      # More information: https://docs.docker.com/reference/compose-file/volumes/
      - /mnt/user/appdata/m3u-editor:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
```

## Container/Host Logs

```log
Error processing "offbug": cURL error 28: Connection timed out after 10001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://subdomain.domain.tld:port/playlist/username/password/m3u_plus
```
