### ISSUE TITLE
Undefined array key 1 (Error) when creating a playlist

### ISSUE THREAD

**Issue by seanpdiaz** [sparkison/m3u-editor#7]
## Describe the bug

When adding a new URL for a playlist that is known good working I keep getting the error "Undefined array key 1" I have tried multiple times to delete the container and start fresh but all attempts yield the same results.

## To Reproduce

1. From the dashboard click on "Playlists" in the left hand column
2. Once redirected to the playlist page click the "New Playlist" button in the upper right corner
3. Add a playlist name (trivial, have tried multiple things) as well as the URL for the m3u playlist
4. Click "Create" in the bottom left of the modal and wait for error to appear in the top notifications tray.

## Expected behavior

I expect that when I click "Create" that the playlist will either be created or a more helpful error will be presented in the user interface.

## Actual behavior

Just get the status of failed in the status column under playlists as well as the notification of the error in the notifications area.

## Screenshots

![Image](https://github.com/user-attachments/assets/a09b863c-949b-4f4c-bd8a-1c897f97daaa)

![Image](https://github.com/user-attachments/assets/5897262b-5911-4606-ba87-f2e1c7e5de07)

## docker-compose.yml contents

```yaml
version: "3.8"
services:
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WWWUSER=sail
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=off
      - M3U_URL_1=http:/***REDACTED***
      - M3U_URL_2=http://***REDACTED***
    volumes:
      - /apps/m3ueditor/config:/var/www/config
    restart: unless-stopped
    ports:
      - 36400:36400 # app
      # - 36790:36790 # for queue (redis server) - not currently used
      - 36800:36800 # websockets/broadcasting
networks: {}
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```
