### ISSUE TITLE
Cannot create new playlist

### ISSUE THREAD

**Issue by gregbert42** [sparkison/m3u-editor#80]
## Describe the bug

Creating a playlist causes a 500 Server error

## To Reproduce

start a new playlist
enter options as usual
create 'create'

happens even when I am creating a blank, custom playlist

![Image](https://github.com/user-attachments/assets/7adba96c-71bd-4c0c-ace6-e67bfc12f8e4)

## docker-compose.yml contents

```yaml

  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=New_York/America
    volumes:
      - /home/remote_fs_user/conf/m3u-editor:/var/www/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
    restart: unless-stopped

```

## Container/Host Logs

LOG: https://paste.c-net.org/ImportsMolecule
