### ISSUE TITLE
EPG is not mapping, but other services map it fine

### ISSUE THREAD

**Issue by gregbert42** [sparkison/m3u-editor#82]
## Describe the bug

The EPG being produced by m3u-editor is no longer working. I have noticed that channel-id and channel are blank in the XML. 
see screenshot

![Image](https://github.com/user-attachments/assets/c12ef8c2-0215-4142-9eb9-7ce899091c3b)

## To Reproduce

Standard:
1. Create a playlist, enable channels i wanted
2. Add in the EPG
3. Map the EPG to channels
4. Use Playlist m3u and epg

## Expected behavior

This work previously. I would expect to see the EPG mapped against shows.

## Actual behavior

Nothing maps.

## docker-compose.yml contents

```yaml
  m3u-editor:
    image: sparkison/m3u-editor:latest
    container_name: m3u-editor
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=New_York/America
    volumes:
      - /home/remote_fs_user/conf/m3u-editor:/var/www/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 36400:36400 # app
      - 36800:36800 # websockets/broadcasting
    restart: unless-stopped

```

## Container/Host Logs

```log
[<!-- Insert logs here -->](https://paste.c-net.org/CashedDugout)
```

## Additional context

Note that i have reported a separate issue related to not being able to create playlists. I do not know if these are related.
